require 'time'
require_relative './tag'


%w(debsign aptrepo rpmsign yumrepo).each do |image|
  desc "Build #{image}"
  task image do
    cd image do
      sh("docker build --tag=gocddev/#{image}:#{DOCKER_TAG} .")
      sh("docker push gocddev/#{image}:#{DOCKER_TAG}")
    end
  end

  task :default => image
end
